services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    networks:
      proxy:
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - JELLYFIN_PublishedServerUrl=192.168.1.110 #optional
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - /merged/jellyfin/config:/config
      - /home/minipc/docker/jellyfin/transcodes:/transcodes
      - /merged/rutorrent/downloads/TV:/data/tvshows:ro
      - /merged/rutorrent/downloads/movies:/data/movies:ro
    ports:
      - 8096:8096
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

networks:
  proxy:
    external: true
