services:
  handbrake:
    image: jlesage/handbrake
    ports:
      - "50800:5800"
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - TZ=Europe/Madrid
      - DARK_MODE=1
      - SECURE_CONNECTION=1
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - "/docker/handbrake/appdata:/config:rw"
      - "/merged/rutorrent/downloads/source:/storage:ro"
      - "/merged/rutorrent/downloads/output:/output:rw"
    restart:
      always
