services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 192.168.1.110:30000:3000
    env_file: .env # use .env
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - ./icons:/app/public/icons # for custom icons
      - /merged:/merged:ro
        # - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations, see alternative methods
    environment:
      PUID: $PUID # read them from .env
      PGID: $PGID # read them from .env
      HOMEPAGE_ALLOWED_HOSTS: 192.168.1.110:30000,192.168.100.1:30000
    restart: always
    security_opt:
      - no-new-privileges:true