networks: # Create a network to communicate both Gotify and Watchtower
  notify-net:

services:
  gotify: # Go to Gotify website first and create a token that will be used on WATCHTOWER_NOTIFICATION_URL
    image: gotify/server
    container_name: gotify
    networks:
      - notify-net
    ports:
      - 8070:80
    volumes:
      - /home/minipc/docker/gotify:/app/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    environment:
      TZ: Europe/Madrid

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    networks:
      - notify-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: Europe/Madrid
      WATCHTOWER_CLEANUP: "true"       # remove old images after update (useful for saving space)
      WATCHTOWER_SCHEDULE: 0 0 4 * * * # run Watchtower every day at 4 am
      # WATCHTOWER_RUN_ONCE: true
      WATCHTOWER_WARN_ON_HEAD_FAILURE: "never"       # Disable HEAD warnings
      WATCHTOWER_DISABLE_CONTAINERS: "jellyfin rtorrent-rutorrent" # disable containers I do not want to be updated automatically
      WATCHTOWER_ROLLING_RESTART: "true"       # you can tell watchtower to do updates and restarts one by one - can be helpful
      WATCHTOWER_NOTIFICATIONS: "shoutrrr"
      WATCHTOWER_NOTIFICATION_URL: "gotify://gotify:80/TOKEN?title=Watchtower&disabletls=yes"
