[Interface]
Address = 192.168.100.1 # replace with your own WireGuard server IP address
ListenPort = 51820
PrivateKey = REDACTED # replace with your own private key
# PostUp and PostDown are used to configure the iptables rules and allow split tunnel on your client. Replace enp1s0 with the name of the network interface you want to use for the WireGuard interface
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o enp1s0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o enp1s0 -j MASQUERADE

[Peer]
# peer1
PublicKey = REDACTED # replace with your own public key
PresharedKey = REDACTED # replace with your own preshared key
AllowedIPs = 192.168.100.2/32
PersistentKeepalive = 25
