services:
  vikunja:
    image: vikunja/vikunja
    ports:
      - 3456:3456
    volumes: 
      - /home/minipc/docker/vikunja/files:/app/vikunja/files
      - /home/minipc/docker/vikunja/config.yaml:/etc/vikunja/config.yml
    networks:
      - proxy
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file: .env # use .env
    volumes:
      - /home/minipc/docker/vikunja/db:/var/lib/mysql
    networks:
      - proxy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"]
      interval: 2s
      start_period: 30s

networks:
  proxy:
    external: true
