services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 8100:8000
      - 9443:9443
        #      - 9900:9000 # for http
    volumes:
      - /home/minipc/docker/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
