---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    label: System
    cpu: true
    memory: true
    cputemp: true
    uptime: true
    units: metric # only used by cpu temp
    refresh: 10000 # optional, in ms

- resources:
    label: Storage
    expanded: true
    disk: 
      - / 
      - /merged
    diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk

- search:
    provider: google # <--- updated with google
    focus: true # Optional, will set focus to the search bar on page load
    showSearchSuggestions: true # Optional, will show search suggestions. Defaults to false
    target: _blank

- datetime:
    text_size: 4xl
    locale: es
    format:
      timeStyle: short
      timeZone: "Europe/Madrid"

- weatherapi:
    latitude: 37.40881
    longitude: -4.48522
    units: metric # or imperial
    provider: weatherapi
    cache: 5 # Time in minutes to cache API responses, to stay within limits
