---
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    network_mode: "host" # used the host network to avoid conflicts with split tunnel
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000 
      - PGID=1000 
      - TZ=Europe/Madrid 
      - PERSISTENTKEEPALIVE_PEERS=all # optional, keep alive peers
      - LOG_CONFS=true # optional, log the configurations
    volumes:
      - /home/minipc/docker/wireguard/config:/config
      - /lib/modules:/lib/modules # optional
    restart: unless-stopped