services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    networks:
      proxy:
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Madrid
      - PUID=1000
      - PGID=1000
    ports:
      - 5055:5055
    volumes:
      - /home/minipc/docker/jellyseer/config:/app/config
    restart: unless-stopped

networks:
  proxy:
    external: true
